---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: mysql-credentials
  namespace: davinciapps
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: external-secretstore
    kind: ClusterSecretStore
  target:
    name: mysql-credentials
    creationPolicy: Owner
  data:
    - secretKey: user
      remoteRef:
        key: prod/Macracoon/Mysql
        property: user
    - secretKey: password
      remoteRef:
        key: prod/Macracoon/Mysql
        property: password
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: github-credentials
  namespace: davinciapps
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: external-secretstore
    kind: ClusterSecretStore
  target:
    name: github-credentials
    creationPolicy: Owner
  data:
    - secretKey: token
      remoteRef:
        key: prod/Macracoon/Github
        property: token
