---
apiVersion: v1
kind: Namespace
metadata:
  name: davinciapps
  labels:
    name: davinciapps
---
apiVersion: v1
kind: Endpoints
metadata:
  name: external-web
  namespace: davinciapps
subsets:
  - addresses:
      - ip: 192.168.1.240
    ports:
      - name: http
        port: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: external-web
  namespace: davinciapps
spec:
  ports:
    - name: http
      port: 8081
      protocol: TCP
      targetPort: 8081
      nodePort: 0
  selector: {}
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: external-web
  namespace: davinciapps
spec:
  entryPoints:
    - web
    - websecure
  routes:
    - kind: Rule
      match: Host(`davinciapps.pyldin601.dev`)
      services:
        - kind: Service
          name: external-web
          port: 8081
  tls:
    certResolver: default
