apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: arbitrary

commonLabels:
  app: superorder-old

resources:
  - namespace.yaml
  - redis.yaml
  - rabbitmq.yaml
  - postgres.yaml
  - postgres-migration.yaml
  - app.yaml
  - app-sealedsecret.yaml
