---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: polyglot-bot-server
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      deployment: polyglot-bot-server
  template:
    metadata:
      labels:
        deployment: polyglot-bot-server
    spec:
      containers:
        - name: polyglot-bot-server
          image: pldin601/polyglot-bot@sha256:fd42ba86d59e2f6ae2bf97d0b0c427ed92434cccbcd18b03f64f49b90b119e60
          env:
            - name: TS_API_KEY
              valueFrom:
                secretKeyRef:
                  name: polyglot-bot-secret
                  key: TS_API_KEY
            - name: TG_BOT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: polyglot-bot-secret
                  key: TG_BOT_TOKEN
