---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: polyglot-bot-server
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      deployment: polyglot-bot-server
  template:
    metadata:
      labels:
        deployment: polyglot-bot-server
    spec:
      containers:
        - name: polyglot-bot-server
          image: pldin601/polyglot-bot@sha256:c45ba845bd81a52b26e29d2c9a0f9e68af2383a35afbef6ced8526ad5942db64
          env:
            - name: TS_API_KEY
              valueFrom:
                secretKeyRef:
                  name: polyglot-bot-secret
                  key: TS_API_KEY
            - name: TG_BOT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: polyglot-bot-secret
                  key: TG_BOT_TOKEN
