---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cinewrax-cinewrax
spec:
  replicas: 1
  selector:
    matchLabels:
      deployment: cinewrax-cinewrax
  template:
    metadata:
      labels:
        deployment: cinewrax-cinewrax
    spec:
      containers:
        - name: cinewrax-cinewrax
          image: pldin601/cinewrax-cinewraxs-cinewrax@sha256:46ca657f2ae6ffb62a48475261232d31f2dd718f7600d00f0ccf7ec1c66e5ee9
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "750m"
          env:
            - name: DUMMY
              value: "0"
---
kind: Service
apiVersion: v1
metadata:
  name: cinewrax-cinewrax
spec:
  selector:
    deployment: cinewrax-cinewrax
  ports:
    - name: http
      protocol: TCP
      port: 3000
      targetPort: 3000
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: cinewrax-cinewrax
  namespace: cinewrax
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`cw.pyldin601.dev`)
      middlewares: []
      services:
        - kind: Service
          name: cinewrax-cinewrax
          port: 3000
          scheme: http
  tls:
    certResolver: default
