apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: arbitrary

commonLabels:
  app: superorder-me

resources:
  - namespace.yaml
  - dockerconfig-sealedsecret.yaml
  - binance-adapter-deployment.yaml
