kind: Service
apiVersion: v1
metadata:
  name: musicloud-postgres-service
spec:
  selector:
    deployment: musicloud-postgres-deployment
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
