apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: dockerconfig
  namespace: myownradio
spec:
  encryptedData:
    .dockerconfigjson: AgDIEzeXbcomL3FqFfIQVVzIzLdQgPH4g0pVF/zRYHc0C/trhM6Uh0GsA8M1IoES9ZM4tGSk8+Irgj/XwkBQfgzodP1FPbqCOdy8C2MMxoGaRLedGTrY03GZJOOhVsEhftQqPj6XR1v7NAMeM9tXfWMW2eaQvnJoCX6BStIJWYXZ0Gmhfz237PsHrsfyOhbyY7SWF+/mL7g74DKs5WBYAHYTpPESbyGu1wjQDXvbiJODZWCClU/KFf4zpvE3lGZ9Ftd2kKWvlvCmLK7xSCqgdWvshE7tvQ5cjEOZ02uMr1wSp682BsKlyu98IWNgh11gihRSkFFYPqoELxUBV+M0FAIbWmHM6JBH7xpVbxtua34scclWki05N3JzA+cnP5++JF4BT9CbiFOej6s5YjNoNbPvpidJDhxUydORZ0WQjHJF2Y75YgRvG/u7NAOsKalBsPQkj2nx0JkAD5VMV8rg8ua1DTdVkb07EPXfdMUGxB6E8fDVB/2m+PMCScbfVxMznlIRDg3YKOido+7GqJuaDbbCqd1VmaULEjlOQKRI6QvJkubao1Q0ALkeeWiLH9kmY/AjOXQOfq6HonBn2W8lLGb/YYiaIxsMFXBnZ9NagxJp+Dw+Q41vup9W0gjATtYJtoJsWZft6LLG0F9Jc7VKfQalNQancyH2Eg61kUVnt+UlHIjrW432tavv4KWT+AgKH3m1tQZrQVyz3dj7E9KbpqyHNKLdJ1Dh4JJDktH4jb4uQJoym5E5mrZXH/PABqfqF+Ktcq32ktzCSXJT6F9ePUB106E/oHldpzNGttZMI7F/ZAzYBX/tz4PasJLBNdoth5FASlXrwkXtJcnTAGRsbjOZOr5pco8D1MPK9CucQPxdr77+zA==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: dockerconfig
      namespace: myownradio
    type: kubernetes.io/dockerconfigjson
