apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: arbitrary

commonLabels:
  app: myownradio

images: []

resources:
  - myownradio-ns.yaml
  - myownradio-dockerconfig-sealedsecret.yaml

  # mysql
  - myownradio-mysql-deployment.yaml
  - myownradio-mysql-service.yaml
  - myownradio-mysql-pvc.yaml
  - myownradio-mysql-configmap.yaml
  - mysql-migration-job.yaml
  - mysql-database-backup.yaml

  # redis
  - redis-deployment.yaml
  - redis-pvc.yaml
  - redis-service.yaml

  # server
  - myownradio-server-deployment.yaml
  - myownradio-server-service.yaml
  - myownradio-server-ingressroute.yaml
  - myownradio-server-pvc.yaml
  - myownradio-server-configmap.yaml
  - myownradio-server-sealedsecret.yaml

  # streamer
  - myownradio-streamer-deployment.yaml
  - myownradio-streamer-service.yaml
  - myownradio-streamer-ingressroute.yaml

  # file-server
  - myownradio-fileserver-deployment.yaml
  - myownradio-fileserver-service.yaml
  - myownradio-fileserver-ingressroute.yaml

  # radio-manager-backend
  - radio-manager-backend-deployment.yaml
  - radio-manager-backend-service.yaml
  - radio-manager-backend-ingressroute.yaml

  # radiomanager-frontend
  - radiomanager-frontend.yaml

  # channel-bot
  - myownradio-channel-bot-sealedsecret.yaml
#  - myownradio-channel-bot.yaml

  # pubsub
  - pubsub-backend-deployment.yaml
