---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: channel-bot-storage
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: channel-bot
spec:
  replicas: 1
  selector:
    matchLabels:
      deployment: channel-bot
  template:
    metadata:
      labels:
        deployment: channel-bot
    spec:
      volumes:
        - name: channel-bot-storage
          persistentVolumeClaim:
            claimName: channel-bot-storage
        - name: channel-bot-host-mount
          hostPath:
            path: /data/radioterio
      containers:
        - name: channel-bot
          image: pldin601/myownradio-channel-bot:latest@sha256:4c0b1733708de13b9df768162a3e60b3109bcf5218b9995ce36466bf3c24007d
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "1024Mi"
              cpu: "1000m"
          env:
            - name: RUTRACKER_USERNAME
              value: "Ted Irens"
            - name: RUTRACKER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: channel-bot-secret
                  key: RUTRACKER_PASSWORD
            - name: TRANSMISSION_RPC_ENDPOINT
              value: http://transmission-rpc.default.svc.cluster.local:9091/transmission/rpc/
            - name: TRANSMISSION_DOWNLOAD_DIRECTORY
              value: /data/radioterio/
            - name: RADIOMANAGER_ENDPOINT
              value: https://radioter.io/
            - name: RADIOMANAGER_USERNAME
              valueFrom:
                secretKeyRef:
                  name: channel-bot-secret
                  key: RADIOMANAGER_USERNAME
            - name: RADIOMANAGER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: channel-bot-secret
                  key: RADIOMANAGER_PASSWORD
            - name: DOWNLOAD_DIRECTORY
              value: /data/radioterio/
            - name: STATE_STORAGE_DIRECTORY
              value: "/var/lib/torrent-bot/storage"
            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: channel-bot-secret
                  key: OPENAI_API_KEY
            - name: RUST_LOG
              value: trace
          volumeMounts:
            - mountPath: "/var/lib/torrent-bot/storage"
              name: channel-bot-storage
            - mountPath: "/data/radioterio"
              name: channel-bot-host-mount
          ports:
            - containerPort: 8080
      imagePullSecrets:
        - name: dockerconfig
