apiVersion: apps/v1
kind: Deployment
metadata:
  name: myownradio-mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      deployment: myownradio-mysql
  template:
    metadata:
      labels:
        deployment: myownradio-mysql
    spec:
      volumes:
        - name: myownradio-mysql-data
          persistentVolumeClaim:
            claimName: myownradio-mysql-data
      containers:
        - name: mysql
          image: mysql:8.0.29-oracle
          resources:
            requests:
              memory: "256Mi"
              cpu: "200m"
            limits:
              memory: "512Mi"
              cpu: "400m"
          env:
            - name: MYSQL_USER
              valueFrom:
                configMapKeyRef:
                  name: myownradio-mysql-configmap
                  key: username
            - name: MYSQL_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: myownradio-mysql-configmap
                  key: password
            - name: MYSQL_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: myownradio-mysql-configmap
                  key: database
            - name: MYSQL_RANDOM_ROOT_PASSWORD
              value: "true"
          volumeMounts:
            - mountPath: "/var/lib/mysql"
              name: myownradio-mysql-data
