---
apiVersion: batch/v1
kind: Job
metadata:
  name: mysql-migration-job-23.09.6087936631-38c8f45
spec:
  completions: 1
  parallelism: 1
  template:
    spec:
      containers:
        - name: migration
          image: pldin601/myownradio-mysql-migration:23.09.6087936631-38c8f45
          env:
            - name: MYSQL_HOST
              value: myownradio-mysql.myownradio.svc.cluster.local
            - name: MYSQL_DB
              valueFrom:
                configMapKeyRef:
                  name: myownradio-mysql-configmap
                  key: database
            - name: MYSQL_USER
              valueFrom:
                configMapKeyRef:
                  name: myownradio-mysql-configmap
                  key: username
            - name: MYSQL_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: myownradio-mysql-configmap
                  key: password
      restartPolicy: OnFailure
