---
kind: Job
apiVersion: batch/v1
metadata:
  name: mysql-backup-cronjob-1
spec:
#  successfulJobsHistoryLimit: 2
#  failedJobsHistoryLimit: 0
#  schedule: "*/5 * * * *"
#  jobTemplate:
#    spec:
      template:
        spec:
          containers:
            - name: mysql-backup
              image: alpine:3.18
              env:
              - name: MYSQL_HOST
                value: myownradio-mysql.myownradio.svc.cluster.local
              - name: MYSQL_DB
                valueFrom:
                  configMapKeyRef:
                    name: myownradio-mysql-configmap
                    key: database
              - name: MYSQL_USER
                valueFrom:
                  configMapKeyRef:
                    name: myownradio-mysql-configmap
                    key: username
              - name: MYSQL_PASSWORD
                valueFrom:
                  configMapKeyRef:
                    name: myownradio-mysql-configmap
                    key: password
              command: ["/bin/sh", "-c"]
              args:
                - |
                  apk add git mysql-client mariadb-connector-c-dev
                  mysqldump -h$MYSQL_HOST -u$MYSQL_USER -p$MYSQL_PASSWORD $MYSQL_DB > myownradio_mysql_backup.sql
          restartPolicy: OnFailure
