---
kind: CronJob
apiVersion: batch/v1
metadata:
  name: mysql-backup-cronjob
  namespace: myownradio
spec:
  successfulJobsHistoryLimit: 2
  failedJobsHistoryLimit: 0
  schedule: "0 12 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: mysql-backup
              image: alpine:3.18
              env:
              - name: MYSQL_HOST
                value: myownradio-mysql.myownradio.svc.cluster.local
              - name: MYSQL_DB
                valueFrom:
                  configMapKeyRef:
                    name: myownradio-mysql-configmap
                    key: database
              - name: MYSQL_USER
                valueFrom:
                  configMapKeyRef:
                    name: myownradio-mysql-configmap
                    key: username
              - name: MYSQL_PASSWORD
                valueFrom:
                  configMapKeyRef:
                    name: myownradio-mysql-configmap
                    key: password
              - name: GITHUB_TOKEN
                valueFrom:
                  secretKeyRef:
                    name: github-token
                    key: token
              command: ["/bin/sh", "-c"]
              args:
                - |
                  apk add git mysql-client mariadb-connector-c-dev &&
                  git config --global user.email "hello@pyldin601.dev" &&
                  git config --global user.name "Backup Bot" &&
                  git clone https://pyldin601:"$GITHUB_TOKEN"@github.com/myownradio/mysql-database-backup.git &&
                  cd mysql-database-backup &&
                  mysqldump --no-create-info --no-tablespaces -h$MYSQL_HOST -u$MYSQL_USER -p$MYSQL_PASSWORD $MYSQL_DB > myownradio_mysql_backup.sql &&
                  git add myownradio_mysql_backup.sql &&
                  git commit -m "Adding new database backup" &&
                  git push &&
                  exit 0
          restartPolicy: OnFailure
