---
kind: Service
apiVersion: v1
metadata:
  name: radiomanager-pubsub-backend
spec:
  selector:
    deployment: radiomanager-pubsub-backend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
