apiVersion: apps/v1
kind: Deployment
metadata:
  name: radio-manager-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      deployment: radio-manager-backend
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
      labels:
        deployment: radio-manager-backend
    spec:
      containers:
        - name: streamer
          image: pldin601/myownradio-radio-manager-backend:22.07.2763292350-b2e0e76
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1024Mi"
              cpu: "750m"
          env:
            - name: BIND_ADDRESS
              value: 0.0.0.0:8080
      imagePullSecrets:
        - name: dockerconfig
