apiVersion: apps/v1
kind: Deployment
metadata:
  name: radio-manager-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      deployment: radio-manager-backend
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
      labels:
        deployment: radio-manager-backend
    spec:
      containers:
        - name: streamer
          image: pldin601/myownradio-radio-manager-backend:23.10.6518017277-292c1ea
          volumeDevices:
            - devicePath: /dev/dri
              name: /dev/dri
          resources:
            requests:
              memory: "512Mi"
              cpu: "190m"
            limits:
              memory: "1024Mi"
              cpu: "500m"
          env:
            - name: BIND_ADDRESS
              value: 0.0.0.0:8080
            - name: MYSQL_USER
              valueFrom:
                configMapKeyRef:
                  name: myownradio-mysql-configmap
                  key: username
            - name: MYSQL_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: myownradio-mysql-configmap
                  key: password
            - name: MYSQL_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: myownradio-mysql-configmap
                  key: database
            - name: MYSQL_HOST
              value: myownradio-mysql.myownradio.svc.cluster.local
            - name: FILE_SERVER_ENDPOINT
              value: https://fs1.radioter.io/
            - name: RADIO_STREAMER_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  name: myownradio-server
                  key: RADIO_STREAMER_INTERNAL_ENDPOINT
            - name: RADIO_STREAMER_TOKEN
              valueFrom:
                secretKeyRef:
                  name: myownradio-server
                  key: RADIO_STREAMER_TOKEN
            - name: FILE_SYSTEM_ROOT_PATH
              value: ""
            - name: PUBSUB_BACKEND_ENDPOINT
              value: http://radiomanager-pubsub-backend.myownradio.svc.cluster.local:8080
      imagePullSecrets:
        - name: dockerconfig
