---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: radio-manager-backend-stripprefix
  namespace: myownradio
spec:
  stripPrefix:
    prefixes: ["/radio-manager/api"]

---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: radio-manager-backend-forwardauth
  namespace: myownradio
spec:
  forwardAuth:
    address: http://myownradio-server.myownradio.svc.cluster.local/api/v2/self
    authResponseHeaders: ["user-id"]
    trustForwardHeader: false

---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: radio-manager-backend
  namespace: myownradio
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`old.myownradio.biz`) && PathPrefix(`/radio-manager/api/`)
      services:
        - kind: Service
          name: radio-manager-backend
          port: 8080
          scheme: http
      middlewares:
        - name: radio-manager-backend-stripprefix
        - name: radio-manager-backend-forwardauth
    - kind: Rule
      match: Host(`old.myownradio.biz`) && PathPrefix(`/radio-manager/api/pub/`)
      services:
        - kind: Service
          name: radio-manager-backend
          port: 8080
          scheme: http
      middlewares:
        - name: radio-manager-backend-stripprefix
  tls:
    certResolver: default
