---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: myownradio-redis-data
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
