apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: dockerconfig
  namespace: superorder-me
spec:
  encryptedData:
    .dockerconfigjson: AgCyoUirasmZtkYqmLgOnHMAH4nMlBWpQdILUASkdm2b8tYUBsqNUiM8Fj5Skul8QVHA+8UFwwEPp42dGoTgYx79Xmbq5QEdasfn/l9Q7nNShXsniOylJgfFpyTo13P70AKOOkBdtIZhuKimYhOOTxqALlnMo9NuCFFalHWCngeDc/nhoKH6T01x8DZtiQGSnjK+Sc77uXX9CnLpCIXvXCGEfN2892gG5mbkF6sGCZ/MNT7Ziz5mEuO/mr5oI0XBJc/1RYcpYCOcFeRjrFCwU9uLWvNbUpqZrVpGxUOMc28uwmb2yzWtskK1Y+fxyBDRAFN2WkHppSneeuohPxU0XfKpDosdjepz63QIq5D01H0E+5qXY8EFa5KND+GKtLvhpFb7RAMFfFUtHptTzj6N7VDhicRK5CQvl3Na/GgrUkTtm88l48/8UhWShWhH6fK7q0EeAeSn5qS8hxrOGVB13wvDhyNEIkswH26EBxpOlHVtxYx9Bj1QAq5Ex9hxZrP5S0AD8rPSWG0GEe8RpLtjKpdCBX7xvE0WNwjNiavIQ74TcmUN91Gy+1cylM/3eBJjQczk+Z1tnH4jzLGmZbjZHzAw9re/gw79gT8/ZAFuvrAnez6l2M9sLymUfKGSPv/+Hbua7rfnNLwoyYqZs4coog63Sz4YeYZp+AMYAM8TR2e1jMHk4SmYRG19Mo5aehJsFcfjrhab5n+KwJ1p36HoFY5RCBAWZ/89iKm1GcgsH6Ft8Lf0ToHo9Z9qlT+zGT7vRoJZ3F6jWfSvucAEVM1IE7n9hr6jobRGucYmJy0wn3DRg7YIERIxhFYXMtpXohKXrKvCzqHY8n37hf9F8da2QU4YZyok9tfEJ6WybSxm41nGvXLnSw==
  template:
    metadata:
      name: dockerconfig
      namespace: superorder-me
    type: kubernetes.io/dockerconfigjson
