apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: dockerconfig
  namespace: superorder-me
spec:
  encryptedData:
    .dockerconfigjson: AgB+mgeSnHdr0DmLmiioa/B7dt2Y2ZzrUg13lIiYGBna9GSTplXu/rl8h1umkZPvOIS2Br+bv5E4IUzNET4SNsugGydjMYSLMbHkmNfyGlIZ1qp7QNqzLT4uOC6Y3n11AuHPANpPRTaNW9tYyAQW7yDFgZW3OlYAjRe0SmAto4mirkx2yvkMtDvLgIb9Pu2B4seDCC6o4E/DvquPelCuqihZQMTjOT5cRlEEipRQrHDI/Zrf4/5OOhElPx3jCgC+jVhf6o4dMKF+ZOQGXJW4Qt28fw9yAorNEDBgq5c5fJPWLcz+EWw+UHIiCz8D/txHp7pTOTPiv8wrHP6U1TVFY8s8Otov/yhv5kl3PfR+SzykWrZNn3sViEVg1AFdWfrin3XD1PgVwKilXy1B+DTUirPCDWxMc/IvuCjk875wk6SZvnvy52nBQUV5QmDc+2XyFpMEl4TlM1Qn65Qm8Goh+CctVknGFNw9ZoKtqq46G1J5G9JdSg+mIFlX9Gth5rzhCTjQ0IilpWYMDFvVAYhxXtECcUz2mZcF3ChBorOs5DNMtJAyXA7bj8lJkTOqqIsfokiYiIitidJmApISoAagHKZj7B52afIO9XP7xySN9xOGj+MNXbA4Rt3JJuSVuAupdErF7HksjuP+C7dJbIx40uH9eIWtyyUW7jOeXqUUMxFj/DWE2szi4QRIOrF2v5ZhAqCnjVgztJtJnwC1AYFISCo/ODM4xiA+e6ZVNK6FBQ31DuUclQfl7KdF3+DoeQ+gPpmVZ1OG4D+ElPgV/+pAlqbzAmQ+O8FdCZ7KqLxSart1X1Lilm7l/earH2plM+o3nCHuM6b8CM2/PpcY6fyOwUGZf1oqdi2rvUiQLQzE1Y8/PN9rYg==
  template:
    metadata:
      creationTimestamp: null
      name: dockerconfig
      namespace: superorder-me
    type: kubernetes.io/dockerconfigjson

