apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: myownradio-mysql-data
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
