apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: myownradio-server-storage
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 128Gi
