apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: arbitrary

commonLabels:
  app: torrent-bot

resources:
  - namespace.yaml
  - transmission-daemon.yaml
  - torrent-bot-runner.yaml
  - torrent-bot-server.yaml
