---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: torrent-bot-runner
spec:
  successfulJobsHistoryLimit: 2
  failedJobsHistoryLimit: 0
  schedule: "5 9-22 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          volumes:
            - name: db-volume
              persistentVolumeClaim:
                claimName: db-volume-claim
          containers:
            - name: torrent-bot
              image: pldin601/torrent-bot-runner@sha256:0b30b02087e8d9d9d0bcdf0a6bcb3114f8cbccb1f3800fa1b09c461c0d3966e6
              volumeMounts:
                - mountPath: /storage
                  name: db-volume
              env:
                - name: STORAGE_FILE
                  value: /storage/torrent-bot.db
                - name: TRANS_URL
                  value: http://transmission-daemon:9091/transmission/rpc
                - name: TRANS_DOWNLOAD_DIRECTORY
                  value: /data
                - name: TOLOKA_USERNAME
                  valueFrom:
                    secretKeyRef:
                      name: toloka-secret
                      key: USERNAME
                - name: TOLOKA_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: toloka-secret
                      key: PASSWORD
                - name: TELEGRAM_BOT_TOKEN
                  valueFrom:
                    secretKeyRef:
                      name: telegram-secret
                      key: TOKEN
                - name: TELEGRAM_BOT_CHAT_ID
                  value: "384980395"
                - name: CLIENT_ENDPOINT
                  value: "http://torrent-bot-server:8080"
                - name: SERVER_ENDPOINT
                  value: "http://torrent-bot-server:8080"
          restartPolicy: OnFailure
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-volume-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
