apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: nginx-lb
spec:
  selector:
    matchLabels:
      deployment: nginx-lb
  template:
    metadata:
      labels:
        deployment: nginx-lb
    spec:
      containers:
        - name: nginx-lb
          image: pldin601/nginx-lb:latest
          imagePullPolicy: Always
          env:
            - name: TARGET_HTTP_HOST
              value: traefik.svc.cluster.local:80
            - name: TARGET_HTTPS_HOST
              value: traefik.svc.cluster.local:443
          ports:
            - containerPort: 80
              hostPort: 80
            - containerPort: 443
              hostPort: 443
