apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: arbitrary

commonLabels:
  app: musicloud

images:
  - name: postgres
    newName: postgres
    newTag: "9.5"

resources:
  - musicloud-postgres-deployment.yaml
  - musicloud-postgres-configmap.yaml
  - musicloud-postgres-pvc.yaml
