apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: musicloud-postgres-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 32Gi
