---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: musicloud-server-public
  namespace: musicloud
spec:
  entryPoints:
    - web
  routes:
    - kind: Rule
      match: Host(`musicloud.homefs.biz`)
      services:
        - kind: Service
          name: musicloud-server-service
          port: 8080
