apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: musicloud-postgres-data-volume-claim
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
