apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: musicloud-server-data-volume-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 32Gi
